<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use App\Models\User;

class SensorTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = User::first();
        $userId = $user ? $user->id : null;

        $sensorTypes = [
            [
                'id' => Str::uuid(),
                'name' => 'Temperature Sensor',
                'description' => 'Measures temperature in various units',
                'category' => 'environmental',
                'data_type' => 'temperature',
                'unit_of_measure' => '°C',
                'min_value' => -50,
                'max_value' => 200,
                'accuracy' => 0.5,
                'response_time' => 3000,
                'is_active' => true,
                'created_by' => $userId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Pressure Sensor',
                'description' => 'Measures pressure in various units',
                'category' => 'process',
                'data_type' => 'pressure',
                'unit_of_measure' => 'PSI',
                'min_value' => 0,
                'max_value' => 1000,
                'accuracy' => 1.0,
                'response_time' => 500,
                'is_active' => true,
                'created_by' => $userId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Vibration Sensor',
                'description' => 'Measures vibration frequency and amplitude',
                'category' => 'mechanical',
                'data_type' => 'vibration',
                'unit_of_measure' => 'Hz',
                'min_value' => 0,
                'max_value' => 2000,
                'accuracy' => 5.0,
                'response_time' => 50,
                'is_active' => true,
                'created_by' => $userId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Flow Sensor',
                'description' => 'Measures flow rate of liquids and gases',
                'category' => 'process',
                'data_type' => 'flow',
                'unit_of_measure' => 'L/min',
                'min_value' => 0,
                'max_value' => 1000,
                'accuracy' => 2.0,
                'response_time' => 1250,
                'is_active' => true,
                'created_by' => $userId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Voltage Sensor',
                'description' => 'Measures electrical voltage',
                'category' => 'electrical',
                'data_type' => 'voltage',
                'unit_of_measure' => 'V',
                'min_value' => 0,
                'max_value' => 600,
                'accuracy' => 1.0,
                'response_time' => 50,
                'is_active' => true,
                'created_by' => $userId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Current Sensor',
                'description' => 'Measures electrical current',
                'category' => 'electrical',
                'data_type' => 'current',
                'unit_of_measure' => 'A',
                'min_value' => 0,
                'max_value' => 200,
                'accuracy' => 1.0,
                'response_time' => 50,
                'is_active' => true,
                'created_by' => $userId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Speed Sensor',
                'description' => 'Measures rotational speed',
                'category' => 'mechanical',
                'data_type' => 'speed',
                'unit_of_measure' => 'RPM',
                'min_value' => 0,
                'max_value' => 5000,
                'accuracy' => 1.0,
                'response_time' => 50,
                'is_active' => true,
                'created_by' => $userId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Level Sensor',
                'description' => 'Measures liquid or solid level',
                'category' => 'process',
                'data_type' => 'level',
                'unit_of_measure' => '%',
                'min_value' => 0,
                'max_value' => 100,
                'accuracy' => 1.0,
                'response_time' => 500,
                'is_active' => true,
                'created_by' => $userId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Humidity Sensor',
                'description' => 'Measures relative humidity',
                'category' => 'environmental',
                'data_type' => 'humidity',
                'unit_of_measure' => '%RH',
                'min_value' => 0,
                'max_value' => 100,
                'accuracy' => 2.0,
                'response_time' => 17500,
                'is_active' => true,
                'created_by' => $userId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Position Sensor',
                'description' => 'Measures position or angle',
                'category' => 'mechanical',
                'data_type' => 'angle',
                'unit_of_measure' => '°',
                'min_value' => 0,
                'max_value' => 360,
                'accuracy' => 0.5,
                'response_time' => 50,
                'is_active' => true,
                'created_by' => $userId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('sensor_types')->insert($sensorTypes);
    }
}
